(cl:defpackage my_robot_msgs-msg
  (:use )
  (:export
   "<COUNTUTILACTION>"
   "COUNTUTILACTION"
   "<COUNTUTILACTIONFEEDBACK>"
   "COUNTUTILACTIONFEEDBACK"
   "<COUNTUTILACTIONGOAL>"
   "COUNTUTILACTIONGOAL"
   "<COUNTUTILACTIONRESULT>"
   "COUNTUTILACTIONRESULT"
   "<COUNTUTILFEEDBACK>"
   "COUNTUTILFEEDBACK"
   "<COUNTUTILGOAL>"
   "COUNTUTILGOAL"
   "<COUNTUTILRESULT>"
   "COUNTUTILRESULT"
  ))

