; Auto-generated. Do not edit!


(cl:in-package my_robot_msgs-msg)


;//! \htmlinclude OdometryFeedback.msg.html

(cl:defclass <OdometryFeedback> (roslisp-msg-protocol:ros-message)
  ((position
    :reader position
    :initarg :position
    :type cl:integer
    :initform 0))
)

(cl:defclass OdometryFeedback (<OdometryFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <OdometryFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'OdometryFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_robot_msgs-msg:<OdometryFeedback> is deprecated: use my_robot_msgs-msg:OdometryFeedback instead.")))

(cl:ensure-generic-function 'position-val :lambda-list '(m))
(cl:defmethod position-val ((m <OdometryFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_msgs-msg:position-val is deprecated.  Use my_robot_msgs-msg:position instead.")
  (position m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <OdometryFeedback>) ostream)
  "Serializes a message object of type '<OdometryFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'position)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <OdometryFeedback>) istream)
  "Deserializes a message object of type '<OdometryFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'position) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<OdometryFeedback>)))
  "Returns string type for a message object of type '<OdometryFeedback>"
  "my_robot_msgs/OdometryFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'OdometryFeedback)))
  "Returns string type for a message object of type 'OdometryFeedback"
  "my_robot_msgs/OdometryFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<OdometryFeedback>)))
  "Returns md5sum for a message object of type '<OdometryFeedback>"
  "7b97bb7ed9a33fb2edbc8c809cbaebf8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'OdometryFeedback)))
  "Returns md5sum for a message object of type 'OdometryFeedback"
  "7b97bb7ed9a33fb2edbc8c809cbaebf8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<OdometryFeedback>)))
  "Returns full string definition for message of type '<OdometryFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int64 position~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'OdometryFeedback)))
  "Returns full string definition for message of type 'OdometryFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int64 position~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <OdometryFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <OdometryFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'OdometryFeedback
    (cl:cons ':position (position msg))
))
