// Generated by gencpp from file my_robot_msgs/CountUtilFeedback.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_COUNTUTILFEEDBACK_H
#define MY_ROBOT_MSGS_MESSAGE_COUNTUTILFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct CountUtilFeedback_
{
  typedef CountUtilFeedback_<ContainerAllocator> Type;

  CountUtilFeedback_()
    : percentage(0.0)  {
    }
  CountUtilFeedback_(const ContainerAllocator& _alloc)
    : percentage(0.0)  {
  (void)_alloc;
    }



   typedef double _percentage_type;
  _percentage_type percentage;





  typedef boost::shared_ptr< ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CountUtilFeedback_

typedef ::my_robot_msgs::CountUtilFeedback_<std::allocator<void> > CountUtilFeedback;

typedef boost::shared_ptr< ::my_robot_msgs::CountUtilFeedback > CountUtilFeedbackPtr;
typedef boost::shared_ptr< ::my_robot_msgs::CountUtilFeedback const> CountUtilFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'my_robot_msgs': ['/home/offworld/ros_study/action_study/catkin_ws/devel/share/my_robot_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46302a97c06fe5a4416c427fe6ee8804";
  }

  static const char* value(const ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46302a97c06fe5a4ULL;
  static const uint64_t static_value2 = 0x416c427fe6ee8804ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/CountUtilFeedback";
  }

  static const char* value(const ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
float64 percentage\n\
\n\
";
  }

  static const char* value(const ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CountUtilFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::CountUtilFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percentage: ";
    Printer<double>::stream(s, indent + "  ", v.percentage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_COUNTUTILFEEDBACK_H
