// Generated by gencpp from file my_robot_msgs/OdometryGoal.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_ODOMETRYGOAL_H
#define MY_ROBOT_MSGS_MESSAGE_ODOMETRYGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct OdometryGoal_
{
  typedef OdometryGoal_<ContainerAllocator> Type;

  OdometryGoal_()
    : position(0)
    , velocity(0.0)  {
    }
  OdometryGoal_(const ContainerAllocator& _alloc)
    : position(0)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _position_type;
  _position_type position;

   typedef double _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::my_robot_msgs::OdometryGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::OdometryGoal_<ContainerAllocator> const> ConstPtr;

}; // struct OdometryGoal_

typedef ::my_robot_msgs::OdometryGoal_<std::allocator<void> > OdometryGoal;

typedef boost::shared_ptr< ::my_robot_msgs::OdometryGoal > OdometryGoalPtr;
typedef boost::shared_ptr< ::my_robot_msgs::OdometryGoal const> OdometryGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::OdometryGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::OdometryGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'my_robot_msgs': ['/home/offworld/ros_study/action_study/catkin_ws/devel/share/my_robot_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::OdometryGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::OdometryGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::OdometryGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::OdometryGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::OdometryGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::OdometryGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::OdometryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8503e3c17c2c09c3a4671e9a2ce595cf";
  }

  static const char* value(const ::my_robot_msgs::OdometryGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8503e3c17c2c09c3ULL;
  static const uint64_t static_value2 = 0xa4671e9a2ce595cfULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::OdometryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/OdometryGoal";
  }

  static const char* value(const ::my_robot_msgs::OdometryGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::OdometryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal\n\
int64 position\n\
float64 velocity\n\
";
  }

  static const char* value(const ::my_robot_msgs::OdometryGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::OdometryGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OdometryGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::OdometryGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::OdometryGoal_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<int64_t>::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_ODOMETRYGOAL_H
