// Generated by gencpp from file my_robot_msgs/OdometryFeedback.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_ODOMETRYFEEDBACK_H
#define MY_ROBOT_MSGS_MESSAGE_ODOMETRYFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct OdometryFeedback_
{
  typedef OdometryFeedback_<ContainerAllocator> Type;

  OdometryFeedback_()
    : position(0)  {
    }
  OdometryFeedback_(const ContainerAllocator& _alloc)
    : position(0)  {
  (void)_alloc;
    }



   typedef int64_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::my_robot_msgs::OdometryFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::OdometryFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct OdometryFeedback_

typedef ::my_robot_msgs::OdometryFeedback_<std::allocator<void> > OdometryFeedback;

typedef boost::shared_ptr< ::my_robot_msgs::OdometryFeedback > OdometryFeedbackPtr;
typedef boost::shared_ptr< ::my_robot_msgs::OdometryFeedback const> OdometryFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::OdometryFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::OdometryFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'my_robot_msgs': ['/home/offworld/ros_study/action_study/catkin_ws/devel/share/my_robot_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::OdometryFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::OdometryFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::OdometryFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::OdometryFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::OdometryFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::OdometryFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::OdometryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b97bb7ed9a33fb2edbc8c809cbaebf8";
  }

  static const char* value(const ::my_robot_msgs::OdometryFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b97bb7ed9a33fb2ULL;
  static const uint64_t static_value2 = 0xedbc8c809cbaebf8ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::OdometryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/OdometryFeedback";
  }

  static const char* value(const ::my_robot_msgs::OdometryFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::OdometryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
int64 position\n\
\n\
";
  }

  static const char* value(const ::my_robot_msgs::OdometryFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::OdometryFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OdometryFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::OdometryFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::OdometryFeedback_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<int64_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_ODOMETRYFEEDBACK_H
